apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: zip-service
    labels:
        app: zip-service
spec:
  selector:
    matchLabels:
      app: zip-service
  replicas: 2
  template:
    metadata:
      labels:
        app: zip-service
    spec:
      containers:
      - name: zip-service
        image: pdincau/zip-service:46
        ports:
        - containerPort: 8080

